language: node_js
node_js:
  - 6.2.1
sudo: false
branches:
  only:
    - master
cache:
  directories:
    - node_modules
notifications:
  email:
    - torstenlink@gmx.de
    - markus.felten@gmx.de
before_install:
  - npm i -g npm@latest
before_script:
  - npm prune
  - npm install -g codecov
script:
  - npm run-script cover
after_script:
  - codecov
after_success:
  - npm run semantic-release
